spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/laptop_store
    username: root
    password: root
  jpa:
    show-sql: true

security:
  jwt:
    token:
      secret-key: LAPTOP_STORE
      access-token-expire-length: 900000        #15 minutes
      refresh-token-expire-length: 2592000000   # 30 days

server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8081